import Foundation

// #1 Verilen Stringin palindrome olup olmadığını kontrol eden bir fonksiyon yazınız.
func isPalindrome(string: String) -> Bool {
    
    //String içindeki noktalama işaretlerini ve boşlukları siler ve case insensitive yapabilmek için gelen stringi lowercased yapar
    var inputString = string.filter{!$0.isWhitespace}.lowercased().components(separatedBy: .punctuationCharacters).joined()
    var controlString = ""
    
    for character in inputString {
        if character == " " {
            continue
        }
        controlString = String(character) + controlString
    }
    
    if controlString == inputString {
        return true
    } else {
        return false
    }
}

print(isPalindrome(string: "RADAR"))
print(isPalindrome(string: "Sir I demand I am a maid named Iris"))
print(isPalindrome(string: "Did Hannah see bees? Hannah did."))
print(isPalindrome(string: "Eva, can I see bees in a cave?"))
print("----------------------------")


// #2 Verilen bir array içerisindeki her bir elemanın sayısını veren bir fonksiyon yazınız.
func countArrayElement<T: Hashable>(array: [T]) {
    
    var elementCounts = [T: Int]()
    
    //input array içerisindeki elementlerleri dictionary'ye atar. Eğer daha önce atanmışsa değerini alır atanmamış(nil) ise 0 verir ve her saydığında 1 ekler.
    for element in array {
        elementCounts[element] = (elementCounts[element] ?? 0) + 1
    }
    
    for element in elementCounts {
        print("\(element.key): \(element.value) times")
    }
}

countArrayElement(array: ["red", "red", "yellow", "blue", "green", "blue", "purple", "red"])
print("----------------------------")
countArrayElement(array: [1, 2, 3, 1, 5, 1, 1, 2, 4, 2, 4, 5])
print("----------------------------")
countArrayElement(array: [true, true, false, true])
print("----------------------------")
countArrayElement(array: [2.0, 2.0, 6.4, 7.2])
print("----------------------------")


// #3 "*" Karakterinden piramit oluşturan fonksiyonu yazınız. Parametre olarak kaç katlı olacağı alınsın.
func createPyramid(numberOfFloor: Int) {
    
    var floorNumber = 1
    let nextFloor = "\n"
    var pyramidString = ""
    
    // input olarak alınan kat sayısı kadar satır oluşturulur. Her satıra bulunduğu kat sayısı kadar * eklenir.
    for _ in 1...numberOfFloor {
        pyramidString += String(repeating: "*", count: floorNumber) + nextFloor
        floorNumber += 1
    }
    print(pyramidString)
}

createPyramid(numberOfFloor: 5)
print("----------------------------")


// #4 Yazdığınız piramit fonksiyonun çıktısını ortalı olacak şekilde yazınız.
func createCenterAlignedPyramid(numberOfFloor: Int) {
    
    var floorNumber = 1
    let nextFloor = "\n"
    var pyramidString = ""
    
    
    for floor in 1...numberOfFloor {
        
        // ilk *'ın başına eklenecek boşluk kat sayısı - bulunulan kat olarak hesaplanır
        let space = String(repeating: " ", count: numberOfFloor - floor)
        let floorElement = String(repeating: "* ", count: floorNumber) + nextFloor
        pyramidString += space + floorElement
        floorNumber += 1
    }
    print(pyramidString)
}

createCenterAlignedPyramid(numberOfFloor: 5)
print("----------------------------")


// projecteuler problem 1
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

func sumOfMultiples(below: Int) -> Int {
    var sum = 0
    
    for number in 1..<below {
        if number % 3 == 0 || number % 5 == 0 {
            sum += number
        }
    }
    return sum
}

print(sumOfMultiples(below: 1000))
print("----------------------------")


// projecteuler problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func fibonacciEvenSum(below: Int) -> Int {
    var sum = 2
    var fibonacciArray = [1, 2]
    
    // fibonacciArray'inde eğer son iki sayının toplamı input sayısından küçükse döngü koşulu sağlamayana kadar toplamı array'e ekler ve çift sayıları toplar
    for _ in 0...Int.max {
        let newNumber = fibonacciArray[fibonacciArray.count-1]+fibonacciArray[fibonacciArray.count-2]
        if newNumber < below {
            fibonacciArray.append(newNumber)
            if newNumber % 2 == 0 {
                sum += newNumber
            }
        } else {
            break
        }
    }
    
    return sum
}

print(fibonacciEvenSum(below: 4000000))
print("----------------------------")


// projecteuler problem 3
// The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143 ?

func largestPrimeFactor(number: Int) -> Int {
    if number == 1 { return -1 }
    var number = number
    var primeFactor = 2
    
    //number 1'e eşitleniceye kadar bölünme kontrolü yapılır ve eğer bölünmezse primeFactor 1 arttırılır
    while number > 1 {
        if number % primeFactor == 0 {
            number /= primeFactor
        }
        else {
            primeFactor += 1
        }
    }
    return primeFactor
}

print(largestPrimeFactor(number: 600851475143))
print("----------------------------")
